
exports.seed = knex => knex('users').del()

    .then(() => knex('users').insert([
      {
        id: 1,
        first_name: 'Austin',
        last_name: 'Matthews',
        user_name: 'Lonedawg007',
        gender: 'Male',
        location: 'Austin, TX',
        developer_type: 'Frontend',
        email: 'AmericanHockeyJesus@gmail.com',
        img_url: 'http://keenthemes.com/preview/metronic/theme/assets/pages/media/profile/profile_user.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS,',
        hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS',
      },
      {
        id: 2,
        first_name: 'April',
        last_name: 'Ludgate',
        user_name: 'April.L',
        gender: 'Female',
        location: 'Detroit, MI',
        developer_type: 'Backend',
        email: 'april.l@parksandrec.gov',
        img_url: 'http://keenthemes.com/preview/metronic/theme/assets/pages/media/profile/profile_user.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS,',
        hashed_password: '',
      },
      {
        id: 3,
        first_name: 'Jeremy',
        last_name: 'Jacobs',
        user_name: 'firstNamesOnly',
        gender: 'Male',
        location: 'San Francisco, CA',
        developer_type: 'Fullstack',
        email: 'twofirstnames@hotmail.com',
        img_url: 'http://keenthemes.com/preview/metronic/theme/assets/pages/media/profile/profile_user.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS,',
        hashed_password: '',
      },
      {
        id: 4,
        first_name: 'Corrin',
        last_name: 'Lynn',
        user_name: 'rhymingScheme',
        gender: 'Other',
        location: 'Portland, OR',
        developer_type: 'Fullstack',
        email: 'flyn@rhymingscheme.com',
        img_url: 'http://keenthemes.com/preview/metronic/theme/assets/pages/media/profile/profile_user.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS,',
        hashed_password: '',
      },
      {
        id: 5,
        first_name: 'Gregory',
        last_name: 'Hanzel',
        user_name: 'pantsOnHead',
        gender: 'Male',
        location: 'Bend, OR',
        developer_type: 'Frontend',
        email: 'cvs2@gmail.com',
        img_url: 'http://keenthemes.com/preview/metronic/theme/assets/pages/media/profile/profile_user.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS,',
        hashed_password: '',
      },
      {
        id: 6,
        first_name: 'Cynthia',
        last_name: 'Bozak',
        user_name: 'secondLineCenter',
        gender: 'female',
        location: 'Portland, OR',
        developer_type: 'Fullstack',
        email: 'bozak.c@gmail.com',
        img_url: 'http://keenthemes.com/preview/metronic/theme/assets/pages/media/profile/profile_user.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS,',
        hashed_password: '',
      },
      {
        id: 7,
        first_name: 'Dwight',
        last_name: 'Schrute',
        user_name: 'Regional_Manager',
        email: 'd.schrute@dmifflin',
        hashed_password: '',
      },

    ])).then(() => {
      return knex.raw(
        "SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));"
      )});
