exports.seed = knex => knex('users').del()

    .then(() => knex('users').insert([
      {
        id: 1,
        first_name: 'Austin',
        last_name: 'Matthews',
        user_name: 'Lonedawg007',
        age: 24,
        gender: 'Male',
        location: 'Austin',
        developer_type: 'Frontend',
        email: 'AmericanHockeyJesus@gmail.com',
        img_url: 'http://keenthemes.com/preview/metronic/theme/assets/pages/media/profile/profile_user.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS',
        hashed_password: '$2a$12$C9AYYmcLVGYlGoO4vSZTPud9ArJwbGRsJ6TUsNULzR48z8fOnTXbS',
      },
      {
        id: 2,
        first_name: 'April',
        last_name: 'Ludgate',
        user_name: 'April.L',
        age: 27,
        gender: 'Female',
        location: 'Austin',
        developer_type: 'Backend',
        email: 'april.l@parksandrec.gov',
        img_url: 'https://firstimpressionscollegeconsulting.files.wordpress.com/2012/07/sharon-epstein-square-2012.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, Java, HTML, CSS',
        hashed_password: '',
      },
      {
        id: 3,
        first_name: 'Jeremy',
        last_name: 'Jacobs',
        user_name: 'firstNamesOnly',
        age: 32,
        gender: 'Male',
        location: 'San Francisco',
        developer_type: 'Fullstack',
        email: 'twofirstnames@hotmail.com',
        img_url: 'https://s3.amazonaws.com/thewinespies-production/uploads/producer/person_photo/975-86ba089b989c6705060071e0b1aa26f4e6f9b101/square_person.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS',
        hashed_password: '',
      },
      {
        id: 4,
        first_name: 'Corrin',
        last_name: 'Lynn',
        user_name: 'rhymingScheme',
        age: 31,
        gender: 'Other',
        location: 'Portland',
        developer_type: 'Fullstack',
        email: 'flyn@rhymingscheme.com',
        img_url: 'http://a5.res.cloudinary.com/allamerican/image/fetch/t_face_s270/http://speakerdata2.s3.amazonaws.com/photo/image/820242/8406380301_97e75994eb_z.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'Python, JavaScript, HTML, CSS',
        hashed_password: '',
      },
      {
        id: 5,
        first_name: 'Gregory',
        last_name: 'Hanzel',
        user_name: 'pantsOnHead',
        age: 76,
        gender: 'Male',
        location: 'Seattle',
        developer_type: 'Frontend',
        email: 'cvs2@gmail.com',
        img_url: 'https://43gk2olgujv1r3cer4fps99q-wpengine.netdna-ssl.com/wp-content/uploads/2017/01/brent-square720x720-1.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'JavaScript, HTML, CSS,',
        hashed_password: '',
      },
      {
        id: 6,
        first_name: 'Cynthia',
        last_name: 'Bozak',
        user_name: 'secondLineCenter',
        age: 54,
        gender: 'Female',
        location: 'Portland',
        developer_type: 'Fullstack',
        email: 'bozak.c@gmail.com',
            img_url: 'https://s3-media1.fl.yelpcdn.com/bphoto/-am-bVSwjZ5S4MdbjpUCMQ/ls.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'R, Python, HTML, CSS',
        hashed_password: '',
      },
      {
        id: 7,
        first_name: 'Terran',
        last_name: 'Marine',
        user_name: 'stimpacker',
        age: 98,
        gender: 'Male',
        location: 'Seattle',
        developer_type: 'Backend',
        email: 'fireup11c@gmail.com',
        img_url: 'https://media.licdn.com/mpr/mpr/shrinknp_400_400/p/8/005/051/3f3/0a2c6ac.jpg',
        twitter: 'https://twitter.com/dhh?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor',
        github: 'https://github.com/mbostock',
        linkedin: 'https://www.linkedin.com',
        bio: 'Grew up in a small town in Oregon, but always wished I was from Texas.',
        skills: 'Java, HTML, CSS, SQL',
        hashed_password: '',
      }

    ]))
    .then(() => {
      return knex.raw(
        "SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));"
      )});
